---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-app-deployment
spec:
  selector:
    matchLabels:
      app: edge-app
  replicas: 2 
  template:
    metadata:
      labels:
        app: edge-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: edge-app-service
spec:
  type: NodePort
  selector:
    app: edge-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30303
